---
version: 2

updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    schedule:
      interval: daily
    directory: /
    groups:
      npm:
        patterns:
          - "*"
