---
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: write # Required for repository checkout and release tag.
      id-token: write # Required for authenticating GitHub Pages.
      pages: write # Required for publishing to GitHub Pages.

    concurrency:
      cancel-in-progress: true
      group: releases

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 24

      - name: Install dependencies
        run: npm clean-install

      - name: Build project
        run: npm run build

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          preview: true

      - name: Deploy to web server
        env:
          SSHHOST: ${{ secrets.SSH_HOST }}
          SSHPASS: ${{ secrets.SSH_PASS }}
          SSHPORT: ${{ secrets.SSH_PORT }}
          SSHUSER: ${{ secrets.SSH_USER }}
          TARGET: ~/domains/www.rdhar.dev/public_html/
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no -p $SSHPORT $SSHUSER@$SSHHOST "rm -rf $TARGET*"
          sshpass -e scp -o StrictHostKeyChecking=no -P $SSHPORT -r dist/. $SSHUSER@$SSHHOST:$TARGET

      - name: Create release tag
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          DATETIME=$(date +'%Y.%m.%d-%H.%M') # Format: YYYY.MM.DD-HH.mm
          tar -czf dist.tar.gz -C dist .
          gh release create "v$DATETIME" --generate-notes 'dist.tar.gz#rdhar.dev'
          echo "View release tag: https://github.com/$GH_REPO/releases/tag/v$DATETIME" >> $GITHUB_STEP_SUMMARY
